
---
deployment:
  tasks:
    # Teste básico para verificar se o deploy funciona
    - echo "🧪 TESTE DE DEPLOY BÁSICO 🧪"
    - echo "📅 Data: $(date)"
    - echo "👤 Usuário: $(whoami)"
    - echo "🏠 Home: $HOME"
    - echo "📍 PWD: $(pwd)"
    - echo ""
    - echo "📂 Conteúdo do diretório:"
    - ls -la
    - echo ""
    - echo "🔍 Verificando app/:"
    - ls -la app/ 2>/dev/null || echo "❌ Pasta app/ não encontrada"
    - echo ""
    - echo "🔍 Verificando package.json:"
    - cat app/package.json 2>/dev/null | head -10 || echo "❌ package.json não encontrado"
    - echo ""
    - echo "✅ Teste básico concluído!"
    - echo "📝 Se você vê estas mensagens, o .cpanel.yml está funcionando."
    - echo ""
    - echo "📋 Próximo passo:"
    - echo "   Substitua .cpanel-test.yml por .cpanel.yml para fazer o deploy completo."
